# Generated by Django 5.1 on 2024-08-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.AddField(
            model_name='task',
            name='color',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='dia',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='hora',
            field=models.CharField(default='', max_length=10),
        ),
    ]
