# Generated by Django 5.1 on 2024-08-28 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_task_completed_task_color_task_dia_task_hora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='actividad',
        ),
    ]
